### PR TITLE
fix(core/toOpenAPISchema): "`anyOf` enum schema is lost" attempt

### LINKED ISSUE #52: [toOpenAPISchema]: `anyOf` enum schema is lost
Currently, after passing a json schema through `toOpenAPISchema`'s convertor, `anyOf` types are now undefined, example:

```json5
{
  raw: {
    type: 'object',
    properties: {
      email: {
        type: 'string',
        pattern: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
      },
      role: { anyOf: [ { const: 'EMPLOYER' }, { const: 'JOB_SEEKER' } ] }
    },
    required: [ 'email', 'role' ]
  },
  converted: {
    type: 'object',
    properties: {
      email: {
        type: 'string',
        pattern: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$',
        '$schema': undefined,
        '$id': undefined,
        'x-$schema': undefined,
        'x-$id': undefined
      },
      role: {
        anyOf: [
          {
            const: undefined,
            '$schema': undefined,
            '$id': undefined,
            enum: [ undefined ],
            'x-const': undefined,
            'x-$schema': undefined,
            'x-$id': undefined
          },
          {
            const: undefined,
            '$schema': undefined,
            '$id': undefined,
            enum: [ undefined ],
            'x-const': undefined,
            'x-$schema': undefined,
            'x-$id': undefined
          }
        ],
        '$schema': undefined,
        '$id': undefined,
        'x-$schema': undefined,
        'x-$id': undefined
      }
    },
    required: [ 'email', 'role' ],
    '$schema': undefined,
    '$id': undefined,
    'x-$schema': undefined,
    'x-$id': undefined
  }
}
```

### PR DESCRIPTION
**Pull request by NamesMT**
Fixes #52.

This PR avoids running unnecessary `rewriteConst` if `enum` property already exists, this also fixes #52, #52 seems be caused because a property path could be walked through by `json-schema-walker` multiple times.

### CODE REVIEW

File: packages/core/src/toOpenAPISchema.ts [hunk 1]
```diff
@@ -359,7 +359,7 @@ function convertExamples(schema: SchemaType) {
 }
 
 function rewriteConst(schema: SchemaType) {
-  if (Object.hasOwnProperty.call(schema, "const")) {
+  if (!Object.hasOwnProperty.call(schema, "enum") && Object.hasOwnProperty.call(schema, "const")) {
     schema.enum = [schema.const];
     schema.const = undefined;
```
Comment (MathurAditya724) [inline packages/core/src/toOpenAPISchema.ts:364]: I think we should assign `schema.const = undefined`, doesn't matter if the enum exists or not as that's not an OpenAPI property.

**Comment by MathurAditya724** [comment]
> #52 seems be caused because a property path could be walked through by `json-schema-walker` multiple times.

Interesting, I will take a look into this. Thanks for the heads up

**Comment by NamesMT** [comment]
> > #52 seems be caused because a property path could be walked through by `json-schema-walker` multiple times.
> 
> Interesting, I will take a look into this. Thanks for the heads up

Hi, Idk if you have looked into it yet but I've change the current fix a bit, to do always do a run to assign `schema.const = undefined` if it have value, like you preferred.

**Comment by MathurAditya724** [comment]
Hey! Thanks for this, I'm merging now!
